import type { SeatHubState } from "./types";

const ids = {
  frank: "u-frank",
  katharina: "u-katharina",
  anna: "u-anna",
  tom: "u-tom",
  maria: "u-maria",
  ion: "u-ion",
  lena: "u-lena",
  markus: "u-markus",
  sofia: "u-sofia",
  max: "u-max",
  david: "u-david",
  elena: "u-elena",
  pAudi: "p-audi",
  pMerc: "p-merc",
  pBmw: "p-bmw",
  part4711: "part-4711",
  part8820: "part-8820",
  part3301: "part-3301",
};

export function createSeedState(): SeatHubState {
  return {
    version: 14,
    currentUserId: ids.anna,
    demoRole: "mitarbeiter",
    departments: [
      { id: "trim-engineering", name: "Trim Engineering", location: "hannover", capacityPercent: 94 },
      { id: "engineering", name: "Engineering", location: "hannover", capacityPercent: 94 },
      { id: "schnittentwicklung", name: "Schnittentwicklung", location: "hannover", capacityPercent: 108 },
      { id: "cad", name: "CAD / Zeichnung", location: "hannover", capacityPercent: 95 },
      { id: "naeherei", name: "Näherei", location: "hannover", capacityPercent: 87 },
      { id: "zuschnitt", name: "Zuschnitt", location: "hannover", capacityPercent: 76 },
      { id: "polsterei", name: "Polsterei", location: "hannover", capacityPercent: 91 },
      { id: "musterbau", name: "Musterbau", location: "hannover", capacityPercent: 88 },
      { id: "dokumentation", name: "Dokumentation", location: "hannover", capacityPercent: 72 },
      { id: "werke", name: "Werke", location: "hannover", capacityPercent: 80 },
      { id: "support", name: "Support", location: "hannover", capacityPercent: 65 },
      { id: "ausbildung", name: "Ausbildung / Azubis", location: "hannover", capacityPercent: 40 },
      { id: "extern", name: "Externe Dienstleister", capacityPercent: 70 },
    ],
    users: [
      {
        id: ids.frank,
        name: "Tobias Kronberg",
        roleLabel: "Komplettsitzleiter",
        departmentId: "trim-engineering",
        location: "hannover",
        demoRole: "manager",
        capacityPercent: 85,
        skills: [
          { name: "Musterbau", level: 5, confirmed: true },
          { name: "Dokumentation", level: 4, confirmed: true },
        ],
      },
      {
        id: ids.katharina,
        name: "Miriam Eller",
        roleLabel: "Leitung Trim Engineering",
        departmentId: "trim-engineering",
        location: "hannover",
        demoRole: "manager",
        capacityPercent: 90,
        skills: [
          { name: "Schnittentwicklung", level: 4, confirmed: true },
          { name: "CAD", level: 3, confirmed: true },
        ],
      },
      {
        id: ids.anna,
        name: "Anna Berger",
        roleLabel: "Näherin / Musterbau",
        departmentId: "naeherei",
        location: "hannover",
        demoRole: "mitarbeiter",
        capacityPercent: 78,
        skills: [
          { name: "Naehen", level: 4, confirmed: true },
          { name: "Leder", level: 4, confirmed: true },
          { name: "Reparatur", level: 3, confirmed: true },
          { name: "Polstern", level: 2, confirmed: false },
        ],
      },
      {
        id: "u-julia",
        name: "Julia Krause",
        roleLabel: "Näherin",
        departmentId: "naeherei",
        location: "hannover",
        demoRole: "mitarbeiter",
        capacityPercent: 74,
        skills: [
          { name: "Naehen", level: 3, confirmed: true },
          { name: "Leder", level: 2, confirmed: true },
        ],
      },
      {
        id: "u-petra",
        name: "Petra Lange",
        roleLabel: "Näherin Spezialnähte",
        departmentId: "naeherei",
        location: "hannover",
        demoRole: "mitarbeiter",
        capacityPercent: 81,
        skills: [
          { name: "Naehen", level: 5, confirmed: true },
          { name: "Leder", level: 4, confirmed: true },
        ],
      },
      {
        id: ids.tom,
        name: "Tom Richter",
        roleLabel: "Schnittentwickler",
        departmentId: "schnittentwicklung",
        location: "hannover",
        demoRole: "engineering",
        capacityPercent: 118,
        skills: [
          { name: "Schnittentwicklung", level: 5, confirmed: true },
          { name: "CAD", level: 5, confirmed: true },
          { name: "Musterbau", level: 3, confirmed: true },
        ],
      },
      {
        id: "u-niklas",
        name: "Niklas Bode",
        roleLabel: "Schnittentwickler",
        departmentId: "schnittentwicklung",
        location: "hannover",
        demoRole: "engineering",
        capacityPercent: 95,
        skills: [
          { name: "Schnittentwicklung", level: 4, confirmed: true },
          { name: "CAD", level: 4, confirmed: true },
        ],
      },
      {
        id: "u-sara",
        name: "Sara Hofmann",
        roleLabel: "CAD-Zeichnerin",
        departmentId: "cad",
        location: "hannover",
        demoRole: "engineering",
        capacityPercent: 88,
        skills: [
          { name: "CAD", level: 5, confirmed: true },
          { name: "Schnittentwicklung", level: 2, confirmed: true },
        ],
      },
      {
        id: "u-marco",
        name: "Marco Berger",
        roleLabel: "CAD-Konstrukteur",
        departmentId: "cad",
        location: "hannover",
        demoRole: "engineering",
        capacityPercent: 76,
        skills: [{ name: "CAD", level: 4, confirmed: true }],
      },
      {
        id: "u-felix",
        name: "Felix Orth",
        roleLabel: "Schnittentwickler Junior",
        departmentId: "schnittentwicklung",
        location: "hannover",
        demoRole: "engineering",
        capacityPercent: 70,
        skills: [
          { name: "Schnittentwicklung", level: 2, confirmed: false },
          { name: "CAD", level: 3, confirmed: true },
        ],
      },
      {
        id: ids.maria,
        name: "Maria Popescu",
        roleLabel: "Teamleitung Näherei",
        departmentId: "naeherei",
        location: "rumaenien",
        demoRole: "mitarbeiter",
        capacityPercent: 85,
        skills: [
          { name: "Naehen", level: 5, confirmed: true },
          { name: "Leder", level: 3, confirmed: true },
          { name: "Reparatur", level: 2, confirmed: true },
        ],
      },
      {
        id: "u-ana",
        name: "Ana Ionescu",
        roleLabel: "Näherin",
        departmentId: "naeherei",
        location: "rumaenien",
        demoRole: "mitarbeiter",
        capacityPercent: 80,
        skills: [{ name: "Naehen", level: 4, confirmed: true }],
      },
      {
        id: "u-irina",
        name: "Irina Dumitru",
        roleLabel: "Näherin",
        departmentId: "naeherei",
        location: "rumaenien",
        demoRole: "mitarbeiter",
        capacityPercent: 76,
        skills: [
          { name: "Naehen", level: 3, confirmed: true },
          { name: "Leder", level: 2, confirmed: true },
        ],
      },
      {
        id: ids.ion,
        name: "Ion Marinescu",
        roleLabel: "Zuschnitt",
        departmentId: "zuschnitt",
        location: "rumaenien",
        demoRole: "mitarbeiter",
        capacityPercent: 65,
        skills: [
          { name: "Zuschnitt", level: 4, confirmed: true },
          { name: "Leder", level: 3, confirmed: true },
        ],
      },
      {
        id: "u-vlad",
        name: "Vlad Stanescu",
        roleLabel: "Zuschnitt CNC",
        departmentId: "zuschnitt",
        location: "rumaenien",
        demoRole: "mitarbeiter",
        capacityPercent: 72,
        skills: [{ name: "Zuschnitt", level: 4, confirmed: true }],
      },
      {
        id: "u-andrei",
        name: "Andrei Radu",
        roleLabel: "Schnittentwicklung RO",
        departmentId: "schnittentwicklung",
        location: "rumaenien",
        demoRole: "engineering",
        capacityPercent: 70,
        skills: [
          { name: "Schnittentwicklung", level: 3, confirmed: true },
          { name: "CAD", level: 3, confirmed: true },
        ],
      },
      {
        id: "u-carmen",
        name: "Carmen Vasile",
        roleLabel: "Engineering RO",
        departmentId: "engineering",
        location: "rumaenien",
        demoRole: "engineering",
        capacityPercent: 68,
        skills: [
          { name: "Musterbau", level: 3, confirmed: true },
          { name: "Dokumentation", level: 2, confirmed: true },
        ],
      },
      {
        id: "u-mihai",
        name: "Mihai Constantinescu",
        roleLabel: "Musterbau RO",
        departmentId: "musterbau",
        location: "rumaenien",
        demoRole: "mitarbeiter",
        capacityPercent: 75,
        skills: [{ name: "Musterbau", level: 3, confirmed: true }],
      },
      {
        id: ids.lena,
        name: "Lena Vogt",
        roleLabel: "Entwicklerin Bezüge",
        departmentId: "engineering",
        location: "hannover",
        demoRole: "engineering",
        capacityPercent: 92,
        skills: [
          { name: "Musterbau", level: 4, confirmed: true },
          { name: "Leder", level: 4, confirmed: true },
          { name: "Dokumentation", level: 3, confirmed: true },
        ],
      },
      {
        id: "u-jonas",
        name: "Jonas Weber",
        roleLabel: "Engineer",
        departmentId: "engineering",
        location: "hannover",
        demoRole: "engineering",
        capacityPercent: 84,
        skills: [
          { name: "CAD", level: 3, confirmed: true },
          { name: "Musterbau", level: 2, confirmed: true },
        ],
      },
      {
        id: ids.markus,
        name: "Markus Klein",
        roleLabel: "Polsterei",
        departmentId: "polsterei",
        location: "hannover",
        demoRole: "mitarbeiter",
        capacityPercent: 91,
        skills: [
          { name: "Polstern", level: 5, confirmed: true },
          { name: "Musterbau", level: 3, confirmed: true },
        ],
      },
      {
        id: "u-timo",
        name: "Timo Brandt",
        roleLabel: "Polsterer",
        departmentId: "polsterei",
        location: "hannover",
        demoRole: "mitarbeiter",
        capacityPercent: 86,
        skills: [{ name: "Polstern", level: 4, confirmed: true }],
      },
      {
        id: "u-lukas",
        name: "Lukas Meier",
        roleLabel: "Zuschnitt",
        departmentId: "zuschnitt",
        location: "hannover",
        demoRole: "mitarbeiter",
        capacityPercent: 79,
        skills: [{ name: "Zuschnitt", level: 4, confirmed: true }],
      },
      {
        id: ids.sofia,
        name: "Sofia Hart",
        roleLabel: "Dokumentation",
        departmentId: "dokumentation",
        location: "hannover",
        demoRole: "mitarbeiter",
        capacityPercent: 70,
        skills: [{ name: "Dokumentation", level: 5, confirmed: true }],
      },
      {
        id: ids.max,
        name: "Max Mustermann",
        roleLabel: "Externer Schnittentwickler",
        departmentId: "extern",
        location: "extern",
        demoRole: "extern",
        company: "SchnittPartner GmbH",
        capacityPercent: 60,
        skills: [
          { name: "Schnittentwicklung", level: 4, confirmed: true },
          { name: "CAD", level: 4, confirmed: true },
        ],
      },
      {
        id: ids.david,
        name: "David Nguyen",
        roleLabel: "Engineer",
        departmentId: "engineering",
        location: "hannover",
        demoRole: "engineering",
        capacityPercent: 88,
        skills: [
          { name: "CAD", level: 4, confirmed: true },
          { name: "Schnittentwicklung", level: 3, confirmed: true },
        ],
      },
      {
        id: ids.elena,
        name: "Elena Weiss",
        roleLabel: "Musterbau",
        departmentId: "musterbau",
        location: "hannover",
        demoRole: "mitarbeiter",
        capacityPercent: 82,
        skills: [
          { name: "Musterbau", level: 4, confirmed: true },
          { name: "Naehen", level: 3, confirmed: true },
        ],
      },
      {
        id: "u-nora",
        name: "Nora Schulz",
        roleLabel: "Musterbau",
        departmentId: "musterbau",
        location: "hannover",
        demoRole: "mitarbeiter",
        capacityPercent: 77,
        skills: [{ name: "Musterbau", level: 3, confirmed: true }],
      },
      {
        id: "u-ben",
        name: "Ben Hartmann",
        roleLabel: "Support / Werk",
        departmentId: "werke",
        location: "hannover",
        demoRole: "mitarbeiter",
        capacityPercent: 60,
        skills: [{ name: "Dokumentation", level: 2, confirmed: true }],
      },
      {
        id: "u-lea",
        name: "Lea Hoffmann",
        roleLabel: "Auszubildende",
        departmentId: "ausbildung",
        location: "hannover",
        demoRole: "mitarbeiter",
        capacityPercent: 40,
        skills: [
          { name: "Naehen", level: 1, confirmed: false },
          { name: "Zuschnitt", level: 1, confirmed: false },
        ],
      },
    ],
    projects: [
      {
        id: "p-daimler",
        code: "W 990",
        name: "Komplettsitz W 990",
        customer: "Daimler",
        status: "entwicklung",
        ampel: "orange",
        locations: ["hannover", "rumaenien"],
        description:
          "Fahrzeugprogramm W 990 – Komplettsitz: Bezug + Struktur/Kunststoff. L/R oft gespiegelt.",
        milestoneLabel: "Muster Reihe 1 Sport",
        milestoneRisk: "Alcantara Sportsitz – Bezug/Kunststoff-Anbindung kritisch.",
        supplyScope: "komplettsitz",
      },
      {
        id: ids.pAudi,
        code: "ABC",
        name: "Programm ABC",
        customer: "Audi",
        status: "musterbau",
        ampel: "rot",
        locations: ["hannover", "rumaenien"],
        description:
          "Bezugslieferant mit Anbindung an die Kunststoffkonstruktion – kein Halbzeug-Lieferant.",
        milestoneLabel: "Mustertermin",
        milestoneRisk: "Mustertermin gefährdet – Schnittentwicklung hinter Plan, Freigabe offen.",
        supplyScope: "bezug_schnittstelle",
      },
      {
        id: ids.pMerc,
        code: "XYZ",
        name: "Programm XYZ",
        customer: "Mercedes",
        status: "entwicklung",
        ampel: "orange",
        locations: ["hannover"],
        description: "Bezug + Anbindung, schlanke Variantenstruktur.",
        milestoneLabel: "CAD-Lieferung",
        milestoneRisk: "Externe Schnittentwicklung verspätet.",
        supplyScope: "bezug_schnittstelle",
      },
      {
        id: ids.pBmw,
        code: "G70",
        name: "Programm G70",
        customer: "BMW",
        status: "entwicklung",
        ampel: "gelb",
        locations: ["hannover", "rumaenien"],
        description: "Nur Bezug – eine Sitzreihe, eine Variante.",
        milestoneLabel: "Materialeingang",
        milestoneRisk: "Materiallieferung offen – beobachten.",
        supplyScope: "bezug",
      },
    ],
    structureNodes: [
      // --- Daimler W 990 ---
      { id: "sn-d-r1", projectId: "p-daimler", parentId: null, type: "sitzreihe", label: "1. Reihe", sortOrder: 1 },
      { id: "sn-d-r2", projectId: "p-daimler", parentId: null, type: "sitzreihe", label: "2. Reihe", sortOrder: 2 },
      { id: "sn-d-r3", projectId: "p-daimler", parentId: null, type: "sitzreihe", label: "3. Reihe", sortOrder: 3 },
      { id: "sn-d-r1-sport", projectId: "p-daimler", parentId: "sn-d-r1", type: "sitzvariante", label: "Sportsitz", sortOrder: 1 },
      { id: "sn-d-r1-normal", projectId: "p-daimler", parentId: "sn-d-r1", type: "sitzvariante", label: "Normalsitz", sortOrder: 2 },
      // Module under Sportsitz
      { id: "sn-d-r1-sport-mod-bezug", projectId: "p-daimler", parentId: "sn-d-r1-sport", type: "modul", label: "Bezug", moduleKind: "bezug", sortOrder: 1 },
      { id: "sn-d-r1-sport-mod-ks", projectId: "p-daimler", parentId: "sn-d-r1-sport", type: "modul", label: "Kunststoff", moduleKind: "kunststoff", sortOrder: 2 },
      { id: "sn-d-r1-sport-mod-schaum", projectId: "p-daimler", parentId: "sn-d-r1-sport", type: "modul", label: "Schaum", moduleKind: "schaum", sortOrder: 3 },
      { id: "sn-d-r1-sport-mod-str", projectId: "p-daimler", parentId: "sn-d-r1-sport", type: "modul", label: "Struktur / Metall", moduleKind: "struktur", sortOrder: 4 },
      { id: "sn-d-r1-sport-alc", projectId: "p-daimler", parentId: "sn-d-r1-sport-mod-bezug", type: "bezugvariante", label: "Alcantara", sortOrder: 1 },
      { id: "sn-d-r1-sport-leder", projectId: "p-daimler", parentId: "sn-d-r1-sport-mod-bezug", type: "bezugvariante", label: "Leder", sortOrder: 2 },
      { id: "sn-d-r1-sport-stoff", projectId: "p-daimler", parentId: "sn-d-r1-sport-mod-bezug", type: "bezugvariante", label: "Stoff", sortOrder: 3 },
      { id: "sn-d-r1-normal-mod-bezug", projectId: "p-daimler", parentId: "sn-d-r1-normal", type: "modul", label: "Bezug", moduleKind: "bezug", sortOrder: 1 },
      { id: "sn-d-r1-normal-kunst", projectId: "p-daimler", parentId: "sn-d-r1-normal-mod-bezug", type: "bezugvariante", label: "Kunstleder", sortOrder: 1 },
      { id: "sn-d-r1-normal-leder", projectId: "p-daimler", parentId: "sn-d-r1-normal-mod-bezug", type: "bezugvariante", label: "Leder", sortOrder: 2 },
      { id: "sn-d-r2-normal", projectId: "p-daimler", parentId: "sn-d-r2", type: "sitzvariante", label: "Normalsitz", sortOrder: 1 },
      { id: "sn-d-r2-mod-bezug", projectId: "p-daimler", parentId: "sn-d-r2-normal", type: "modul", label: "Bezug", moduleKind: "bezug", sortOrder: 1 },
      { id: "sn-d-r2-normal-leder", projectId: "p-daimler", parentId: "sn-d-r2-mod-bezug", type: "bezugvariante", label: "Leder", sortOrder: 1 },
      { id: "sn-d-r2-normal-stoff", projectId: "p-daimler", parentId: "sn-d-r2-mod-bezug", type: "bezugvariante", label: "Stoff", sortOrder: 2 },
      { id: "sn-d-r3-bank", projectId: "p-daimler", parentId: "sn-d-r3", type: "sitzvariante", label: "Sitzbank", sortOrder: 1 },
      { id: "sn-d-r3-mod-bezug", projectId: "p-daimler", parentId: "sn-d-r3-bank", type: "modul", label: "Bezug", moduleKind: "bezug", sortOrder: 1 },
      { id: "sn-d-r3-bank-stoff", projectId: "p-daimler", parentId: "sn-d-r3-mod-bezug", type: "bezugvariante", label: "Stoff", sortOrder: 1 },

      // --- Audi ABC: Bezug + Anbindung ---
      { id: "sn-a-r1", projectId: ids.pAudi, parentId: null, type: "sitzreihe", label: "1. Reihe", sortOrder: 1 },
      { id: "sn-a-r1-sport", projectId: ids.pAudi, parentId: "sn-a-r1", type: "sitzvariante", label: "Sportsitz", sortOrder: 1 },
      { id: "sn-a-r1-mod-bezug", projectId: ids.pAudi, parentId: "sn-a-r1-sport", type: "modul", label: "Bezug", moduleKind: "bezug", sortOrder: 1 },
      { id: "sn-a-r1-mod-ss", projectId: ids.pAudi, parentId: "sn-a-r1-sport", type: "modul", label: "Anbindung Kunststoff", moduleKind: "schnittstelle", sortOrder: 2 },
      { id: "sn-a-r1-sport-alc", projectId: ids.pAudi, parentId: "sn-a-r1-mod-bezug", type: "bezugvariante", label: "Alcantara", sortOrder: 1 },
      { id: "sn-a-r1-sport-leder", projectId: ids.pAudi, parentId: "sn-a-r1-mod-bezug", type: "bezugvariante", label: "Leder", sortOrder: 2 },
      { id: "sn-a-r2", projectId: ids.pAudi, parentId: null, type: "sitzreihe", label: "2. Reihe", sortOrder: 2 },
      { id: "sn-a-r2-normal", projectId: ids.pAudi, parentId: "sn-a-r2", type: "sitzvariante", label: "Normalsitz", sortOrder: 1 },
      { id: "sn-a-r2-mod-bezug", projectId: ids.pAudi, parentId: "sn-a-r2-normal", type: "modul", label: "Bezug", moduleKind: "bezug", sortOrder: 1 },
      { id: "sn-a-r2-normal-leder", projectId: ids.pAudi, parentId: "sn-a-r2-mod-bezug", type: "bezugvariante", label: "Leder", sortOrder: 1 },

      // --- Mercedes XYZ ---
      { id: "sn-m-r1", projectId: ids.pMerc, parentId: null, type: "sitzreihe", label: "1. Reihe", sortOrder: 1 },
      { id: "sn-m-r1-ind", projectId: ids.pMerc, parentId: "sn-m-r1", type: "sitzvariante", label: "Individuell", sortOrder: 1 },
      { id: "sn-m-r1-mod-bezug", projectId: ids.pMerc, parentId: "sn-m-r1-ind", type: "modul", label: "Bezug", moduleKind: "bezug", sortOrder: 1 },
      { id: "sn-m-r1-mod-ss", projectId: ids.pMerc, parentId: "sn-m-r1-ind", type: "modul", label: "Anbindung", moduleKind: "schnittstelle", sortOrder: 2 },
      { id: "sn-m-r1-ind-leder", projectId: ids.pMerc, parentId: "sn-m-r1-mod-bezug", type: "bezugvariante", label: "Leder", sortOrder: 1 },
      { id: "sn-m-r2", projectId: ids.pMerc, parentId: null, type: "sitzreihe", label: "2. Reihe", sortOrder: 2 },
      { id: "sn-m-r2-normal", projectId: ids.pMerc, parentId: "sn-m-r2", type: "sitzvariante", label: "Normalsitz", sortOrder: 1 },
      { id: "sn-m-r2-mod-bezug", projectId: ids.pMerc, parentId: "sn-m-r2-normal", type: "modul", label: "Bezug", moduleKind: "bezug", sortOrder: 1 },
      { id: "sn-m-r2-normal-kunst", projectId: ids.pMerc, parentId: "sn-m-r2-mod-bezug", type: "bezugvariante", label: "Kunstleder", sortOrder: 1 },

      // --- BMW G70 (nur Bezug) ---
      { id: "sn-b-r1", projectId: ids.pBmw, parentId: null, type: "sitzreihe", label: "1. Reihe", sortOrder: 1 },
      { id: "sn-b-r1-normal", projectId: ids.pBmw, parentId: "sn-b-r1", type: "sitzvariante", label: "Normalsitz", sortOrder: 1 },
      { id: "sn-b-r1-mod-bezug", projectId: ids.pBmw, parentId: "sn-b-r1-normal", type: "modul", label: "Bezug", moduleKind: "bezug", sortOrder: 1 },
      { id: "sn-b-r1-normal-leder", projectId: ids.pBmw, parentId: "sn-b-r1-mod-bezug", type: "bezugvariante", label: "Leder", sortOrder: 1 },
    ],
    parts: [
      // Daimler – Alcantara L entwickelt, R Spiegel
      {
        id: "part-w990-s-alc-l",
        partNumber: "A990-1S-ALC-L",
        name: "Sportsitz Alcantara Links",
        projectId: "p-daimler",
        structureNodeId: "sn-d-r1-sport-alc",
        side: "links",
        moduleKind: "bezug",
        partKind: "hauptteil",
        engineerUserId: ids.david,
        coverDeveloperUserId: ids.lena,
        currentRevision: "04",
        releasedRevision: "03",
        developmentRole: "entwickelt",
        mirrorPairPartId: "part-w990-s-alc-r",
      },
      {
        id: "part-w990-s-alc-r",
        partNumber: "A990-1S-ALC-R",
        name: "Sportsitz Alcantara Rechts",
        projectId: "p-daimler",
        structureNodeId: "sn-d-r1-sport-alc",
        side: "rechts",
        moduleKind: "bezug",
        partKind: "hauptteil",
        engineerUserId: ids.david,
        coverDeveloperUserId: ids.lena,
        currentRevision: "04",
        releasedRevision: "03",
        developmentRole: "spiegel",
        mirrorMasterPartId: "part-w990-s-alc-l",
        mirrorPairPartId: "part-w990-s-alc-l",
      },
      // Geteiltes Profil: Alcantara + Leder + Stoff identisch – Änderung wirkt auf alle
      {
        id: "part-w990-alc-l-p01",
        partNumber: "A990-OKR-SITZ",
        name: "OKR-Kurzschlussprofil Sitzseite (geteilt)",
        projectId: "p-daimler",
        structureNodeId: "sn-d-r1-sport-mod-bezug",
        side: "einzeln",
        moduleKind: "profil",
        partKind: "profil",
        parentPartId: "part-w990-s-alc-l",
        usedOnPartIds: ["part-w990-s-alc-l", "part-w990-s-led-l", "part-w990-s-stof-l"],
        componentRole:
          "OKR-Kurzschlussprofil – identisch an Alcantara, Leder und Stoff (Befestigung am Schaum)",
        engineerUserId: ids.david,
        coverDeveloperUserId: ids.lena,
        currentRevision: "02",
        releasedRevision: "02",
        developmentRole: "eigenstaendig",
      },
      {
        id: "part-w990-alc-l-p02",
        partNumber: "A990-ALC-L-P02",
        name: "OKR-Kurzschlussprofil Lehnenseite",
        projectId: "p-daimler",
        structureNodeId: "sn-d-r1-sport-alc",
        side: "einzeln",
        moduleKind: "profil",
        partKind: "profil",
        parentPartId: "part-w990-s-alc-l",
        usedOnPartIds: ["part-w990-s-alc-l"],
        componentRole: "OKR-Kurzschlussprofil – Befestigung Bezug am Schaum (Lehne) – nur Alcantara",
        engineerUserId: ids.david,
        coverDeveloperUserId: ids.lena,
        currentRevision: "02",
        releasedRevision: "01",
        developmentRole: "eigenstaendig",
      },
      {
        id: "part-w990-alc-l-p03",
        partNumber: "A990-ALC-L-P03",
        name: "OKR-Profil Seitenwange",
        projectId: "p-daimler",
        structureNodeId: "sn-d-r1-sport-alc",
        side: "einzeln",
        moduleKind: "profil",
        partKind: "profil",
        parentPartId: "part-w990-s-alc-l",
        usedOnPartIds: ["part-w990-s-alc-l"],
        componentRole: "Profil Seitenwange – am Bezug angenäht",
        engineerUserId: "u-jonas",
        coverDeveloperUserId: ids.lena,
        currentRevision: "01",
        developmentRole: "eigenstaendig",
      },
      {
        id: "part-w990-alc-l-p04",
        partNumber: "A990-ALC-L-P04",
        name: "Draht / Clip-Profil Abschluss",
        projectId: "p-daimler",
        structureNodeId: "sn-d-r1-sport-alc",
        side: "einzeln",
        moduleKind: "profil",
        partKind: "befestigung",
        parentPartId: "part-w990-s-alc-l",
        usedOnPartIds: ["part-w990-s-alc-l"],
        componentRole: "Befestigungsprofil Abschlusskante",
        engineerUserId: ids.david,
        coverDeveloperUserId: ids.lena,
        currentRevision: "01",
        developmentRole: "eigenstaendig",
      },
      {
        id: "part-w990-s-led-l",
        partNumber: "A990-1S-LED-L",
        name: "Sportsitz Leder Links",
        projectId: "p-daimler",
        structureNodeId: "sn-d-r1-sport-leder",
        side: "links",
        moduleKind: "bezug",
        partKind: "hauptteil",
        engineerUserId: ids.david,
        coverDeveloperUserId: ids.lena,
        currentRevision: "02",
        releasedRevision: "01",
        developmentRole: "entwickelt",
        mirrorPairPartId: "part-w990-s-led-r",
      },
      {
        id: "part-w990-s-led-r",
        partNumber: "A990-1S-LED-R",
        name: "Sportsitz Leder Rechts",
        projectId: "p-daimler",
        structureNodeId: "sn-d-r1-sport-leder",
        side: "rechts",
        moduleKind: "bezug",
        partKind: "hauptteil",
        engineerUserId: "u-jonas",
        coverDeveloperUserId: ids.lena,
        currentRevision: "02",
        releasedRevision: "01",
        developmentRole: "spiegel",
        mirrorMasterPartId: "part-w990-s-led-l",
        mirrorPairPartId: "part-w990-s-led-l",
      },
      {
        id: "part-w990-s-stof-l",
        partNumber: "A990-1S-STF-L",
        name: "Sportsitz Stoff Links",
        projectId: "p-daimler",
        structureNodeId: "sn-d-r1-sport-stoff",
        side: "links",
        moduleKind: "bezug",
        partKind: "hauptteil",
        engineerUserId: ids.david,
        coverDeveloperUserId: ids.lena,
        currentRevision: "01",
        developmentRole: "entwickelt",
        mirrorPairPartId: "part-w990-s-stof-r",
      },
      {
        id: "part-w990-s-stof-r",
        partNumber: "A990-1S-STF-R",
        name: "Sportsitz Stoff Rechts",
        projectId: "p-daimler",
        structureNodeId: "sn-d-r1-sport-stoff",
        side: "rechts",
        moduleKind: "bezug",
        partKind: "hauptteil",
        engineerUserId: ids.david,
        coverDeveloperUserId: ids.lena,
        currentRevision: "01",
        developmentRole: "spiegel",
        mirrorMasterPartId: "part-w990-s-stof-l",
        mirrorPairPartId: "part-w990-s-stof-l",
      },
      // Kunststoff + Schaum + Struktur unter Sportsitz (Komplettsitz)
      {
        id: "part-w990-ks-schale",
        partNumber: "A990-1S-KS-01",
        name: "Kunststoffschale Sportsitz",
        projectId: "p-daimler",
        structureNodeId: "sn-d-r1-sport-mod-ks",
        side: "einzeln",
        moduleKind: "kunststoff",
        partKind: "hauptteil",
        engineerUserId: ids.david,
        currentRevision: "02",
        releasedRevision: "02",
        developmentRole: "eigenstaendig",
        interfaceNote: "Anbindung Bezug Alcantara/Leder/Stoff – Kontur freigegeben Rev. 02",
      },
      {
        id: "part-w990-schaum-sitz",
        partNumber: "A990-1S-SCH-S",
        name: "Sitzschaum Sportsitz",
        projectId: "p-daimler",
        structureNodeId: "sn-d-r1-sport-mod-schaum",
        side: "einzeln",
        moduleKind: "schaum",
        partKind: "schaum",
        engineerUserId: ids.david,
        currentRevision: "03",
        releasedRevision: "02",
        developmentRole: "eigenstaendig",
        interfaceNote: "OKR-Profile greifen in Kanäle – Kontur mit Bezug abstimmen",
      },
      {
        id: "part-w990-schaum-lehne",
        partNumber: "A990-1S-SCH-L",
        name: "Lehnenschaum Sportsitz",
        projectId: "p-daimler",
        structureNodeId: "sn-d-r1-sport-mod-schaum",
        side: "einzeln",
        moduleKind: "schaum",
        partKind: "schaum",
        engineerUserId: "u-jonas",
        currentRevision: "02",
        releasedRevision: "02",
        developmentRole: "eigenstaendig",
      },
      {
        id: "part-w990-str-frame",
        partNumber: "A990-1S-ST-01",
        name: "Sitzstruktur Sportsitz",
        projectId: "p-daimler",
        structureNodeId: "sn-d-r1-sport-mod-str",
        side: "einzeln",
        moduleKind: "struktur",
        partKind: "hauptteil",
        engineerUserId: ids.david,
        currentRevision: "01",
        developmentRole: "eigenstaendig",
      },
      {
        id: "part-w990-n-kun-l",
        partNumber: "A990-1N-KUN-L",
        name: "Normalsitz Kunstleder Links",
        projectId: "p-daimler",
        structureNodeId: "sn-d-r1-normal-kunst",
        side: "links",
        moduleKind: "bezug",
        engineerUserId: "u-jonas",
        coverDeveloperUserId: ids.lena,
        currentRevision: "01",
        developmentRole: "entwickelt",
        mirrorPairPartId: "part-w990-n-kun-r",
      },
      {
        id: "part-w990-n-kun-r",
        partNumber: "A990-1N-KUN-R",
        name: "Normalsitz Kunstleder Rechts",
        projectId: "p-daimler",
        structureNodeId: "sn-d-r1-normal-kunst",
        side: "rechts",
        moduleKind: "bezug",
        engineerUserId: "u-jonas",
        coverDeveloperUserId: ids.lena,
        currentRevision: "01",
        developmentRole: "spiegel",
        mirrorMasterPartId: "part-w990-n-kun-l",
        mirrorPairPartId: "part-w990-n-kun-l",
      },
      {
        id: "part-w990-n-led-l",
        partNumber: "A990-1N-LED-L",
        name: "Normalsitz Leder Links",
        projectId: "p-daimler",
        structureNodeId: "sn-d-r1-normal-leder",
        side: "links",
        moduleKind: "bezug",
        engineerUserId: ids.david,
        coverDeveloperUserId: ids.lena,
        currentRevision: "01",
        developmentRole: "entwickelt",
        mirrorPairPartId: "part-w990-n-led-r",
      },
      {
        id: "part-w990-n-led-r",
        partNumber: "A990-1N-LED-R",
        name: "Normalsitz Leder Rechts",
        projectId: "p-daimler",
        structureNodeId: "sn-d-r1-normal-leder",
        side: "rechts",
        moduleKind: "bezug",
        engineerUserId: ids.david,
        coverDeveloperUserId: ids.lena,
        currentRevision: "01",
        developmentRole: "spiegel",
        mirrorMasterPartId: "part-w990-n-led-l",
        mirrorPairPartId: "part-w990-n-led-l",
      },
      {
        id: "part-w990-2-led-l",
        partNumber: "A990-2N-LED-L",
        name: "2. Reihe Leder Links",
        projectId: "p-daimler",
        structureNodeId: "sn-d-r2-normal-leder",
        side: "links",
        moduleKind: "bezug",
        engineerUserId: "u-carmen",
        coverDeveloperUserId: ids.lena,
        currentRevision: "01",
        developmentRole: "entwickelt",
        mirrorPairPartId: "part-w990-2-led-r",
      },
      {
        id: "part-w990-2-led-r",
        partNumber: "A990-2N-LED-R",
        name: "2. Reihe Leder Rechts",
        projectId: "p-daimler",
        structureNodeId: "sn-d-r2-normal-leder",
        side: "rechts",
        moduleKind: "bezug",
        engineerUserId: "u-carmen",
        coverDeveloperUserId: ids.lena,
        currentRevision: "01",
        developmentRole: "spiegel",
        mirrorMasterPartId: "part-w990-2-led-l",
        mirrorPairPartId: "part-w990-2-led-l",
      },
      {
        id: "part-w990-2-stof",
        partNumber: "A990-2N-STF",
        name: "2. Reihe Stoff Bank",
        projectId: "p-daimler",
        structureNodeId: "sn-d-r2-normal-stoff",
        side: "einzeln",
        moduleKind: "bezug",
        engineerUserId: "u-carmen",
        coverDeveloperUserId: ids.lena,
        currentRevision: "01",
        developmentRole: "eigenstaendig",
      },
      {
        id: "part-w990-3-stof",
        partNumber: "A990-3B-STF",
        name: "3. Reihe Sitzbank Stoff",
        projectId: "p-daimler",
        structureNodeId: "sn-d-r3-bank-stoff",
        side: "einzeln",
        moduleKind: "bezug",
        engineerUserId: ids.david,
        coverDeveloperUserId: ids.lena,
        currentRevision: "01",
        developmentRole: "eigenstaendig",
      },

      // Audi – Bezug + Anbindung (kein eigenes Kunststoff-Modul)
      {
        id: ids.part4711,
        partNumber: "4711",
        name: "Kopfstütze Sportsitz Alcantara",
        projectId: ids.pAudi,
        structureNodeId: "sn-a-r1-sport-alc",
        side: "einzeln",
        moduleKind: "bezug",
        engineerUserId: ids.david,
        coverDeveloperUserId: ids.lena,
        currentRevision: "07",
        releasedRevision: "05",
        developmentRole: "eigenstaendig",
      },
      {
        id: "part-audi-bezug-l",
        partNumber: "ABC-1S-ALC-L",
        name: "Bezug Sportsitz Alcantara Links",
        projectId: ids.pAudi,
        structureNodeId: "sn-a-r1-sport-alc",
        side: "links",
        moduleKind: "bezug",
        engineerUserId: ids.david,
        coverDeveloperUserId: ids.lena,
        currentRevision: "04",
        releasedRevision: "04",
        developmentRole: "entwickelt",
        mirrorPairPartId: "part-audi-bezug-r",
      },
      {
        id: "part-audi-bezug-r",
        partNumber: "ABC-1S-ALC-R",
        name: "Bezug Sportsitz Alcantara Rechts",
        projectId: ids.pAudi,
        structureNodeId: "sn-a-r1-sport-alc",
        side: "rechts",
        moduleKind: "bezug",
        engineerUserId: ids.david,
        coverDeveloperUserId: ids.lena,
        currentRevision: "04",
        developmentRole: "spiegel",
        mirrorMasterPartId: "part-audi-bezug-l",
        mirrorPairPartId: "part-audi-bezug-l",
      },
      {
        id: "part-audi-led-l",
        partNumber: "ABC-1S-LED-L",
        name: "Bezug Sportsitz Leder Links",
        projectId: ids.pAudi,
        structureNodeId: "sn-a-r1-sport-leder",
        side: "links",
        moduleKind: "bezug",
        engineerUserId: "u-jonas",
        coverDeveloperUserId: ids.lena,
        currentRevision: "02",
        developmentRole: "entwickelt",
        mirrorPairPartId: "part-audi-led-r",
      },
      {
        id: "part-audi-led-r",
        partNumber: "ABC-1S-LED-R",
        name: "Bezug Sportsitz Leder Rechts",
        projectId: ids.pAudi,
        structureNodeId: "sn-a-r1-sport-leder",
        side: "rechts",
        moduleKind: "bezug",
        engineerUserId: "u-jonas",
        coverDeveloperUserId: ids.lena,
        currentRevision: "02",
        developmentRole: "spiegel",
        mirrorMasterPartId: "part-audi-led-l",
        mirrorPairPartId: "part-audi-led-l",
      },
      {
        id: "part-audi-ss-ks",
        partNumber: "ABC-1S-SS-KS",
        name: "Anbindung Kunststoffschale (extern)",
        projectId: ids.pAudi,
        structureNodeId: "sn-a-r1-mod-ss",
        side: "einzeln",
        moduleKind: "schnittstelle",
        engineerUserId: ids.david,
        coverDeveloperUserId: ids.lena,
        currentRevision: "02",
        developmentRole: "eigenstaendig",
        interfaceNote:
          "Externe Kunststoff-TN. Bezugsentwickler stimmt Anbindung ab – kein eigener KS-Lieferumfang.",
      },
      {
        id: "part-audi-r2",
        partNumber: "ABC-2N-LED-L",
        name: "2. Reihe Leder Links",
        projectId: ids.pAudi,
        structureNodeId: "sn-a-r2-normal-leder",
        side: "links",
        moduleKind: "bezug",
        engineerUserId: "u-jonas",
        coverDeveloperUserId: ids.lena,
        currentRevision: "01",
        developmentRole: "entwickelt",
      },

      // Mercedes
      {
        id: ids.part8820,
        partNumber: "8820",
        name: "Seitenwange Individuell Leder Links",
        projectId: ids.pMerc,
        structureNodeId: "sn-m-r1-ind-leder",
        side: "links",
        moduleKind: "bezug",
        engineerUserId: ids.david,
        coverDeveloperUserId: ids.lena,
        currentRevision: "03",
        developmentRole: "entwickelt",
        mirrorPairPartId: "part-merc-r1-r",
      },
      {
        id: "part-merc-r1-r",
        partNumber: "XYZ-1I-LED-R",
        name: "Seitenwange Individuell Leder Rechts",
        projectId: ids.pMerc,
        structureNodeId: "sn-m-r1-ind-leder",
        side: "rechts",
        moduleKind: "bezug",
        engineerUserId: ids.david,
        coverDeveloperUserId: ids.lena,
        currentRevision: "03",
        developmentRole: "spiegel",
        mirrorMasterPartId: ids.part8820,
        mirrorPairPartId: ids.part8820,
      },
      {
        id: "part-merc-ss",
        partNumber: "XYZ-1I-SS",
        name: "Anbindung Struktur (extern)",
        projectId: ids.pMerc,
        structureNodeId: "sn-m-r1-mod-ss",
        side: "einzeln",
        moduleKind: "schnittstelle",
        engineerUserId: ids.david,
        coverDeveloperUserId: ids.lena,
        currentRevision: "01",
        developmentRole: "eigenstaendig",
        interfaceNote: "Anbindungsmaße für Bezug – Struktur kommt vom Kunden/Partner.",
      },
      {
        id: "part-merc-r2",
        partNumber: "XYZ-2N-KUN-L",
        name: "2. Reihe Kunstleder Links",
        projectId: ids.pMerc,
        structureNodeId: "sn-m-r2-normal-kunst",
        side: "links",
        moduleKind: "bezug",
        engineerUserId: "u-jonas",
        coverDeveloperUserId: ids.lena,
        currentRevision: "01",
        developmentRole: "eigenstaendig",
      },

      // BMW – nur Bezug, L entwickelt / R Spiegel
      {
        id: ids.part3301,
        partNumber: "3301",
        name: "Sitzfläche Leder Links",
        projectId: ids.pBmw,
        structureNodeId: "sn-b-r1-normal-leder",
        side: "links",
        moduleKind: "bezug",
        engineerUserId: ids.david,
        coverDeveloperUserId: ids.lena,
        currentRevision: "02",
        developmentRole: "entwickelt",
        mirrorPairPartId: "part-bmw-r",
      },
      {
        id: "part-bmw-r",
        partNumber: "G70-1N-LED-R",
        name: "Sitzfläche Leder Rechts",
        projectId: ids.pBmw,
        structureNodeId: "sn-b-r1-normal-leder",
        side: "rechts",
        moduleKind: "bezug",
        engineerUserId: ids.david,
        coverDeveloperUserId: ids.lena,
        currentRevision: "02",
        developmentRole: "spiegel",
        mirrorMasterPartId: ids.part3301,
        mirrorPairPartId: ids.part3301,
      },
    ],
    revisions: [
      // Kopfstütze 4711 – lange Historie
      {
        id: "rev-01",
        partId: ids.part4711,
        revision: "01",
        title: "Erstentwicklung",
        date: "2019-03-12",
        createdByUserId: ids.david,
        userType: "intern",
        reason: "Erstentwicklung",
        status: "ersetzt",
        drawings: ["Zeichnung_4711_Stand01.pdf", "CAD_4711_REV01"],
        photos: ["Foto_Muster_01"],
        documents: ["Lastenheft_Auszug.pdf"],
        bomItems: ["Bezug Vorderseite", "Schaum Einlage", "Garn X"],
        files: ["CAD_4711_REV01", "Schnitt_4711_REV01"],
      },
      {
        id: "rev-02",
        partId: ids.part4711,
        revision: "02",
        title: "Anpassung Polsterung",
        date: "2019-09-04",
        createdByUserId: ids.lena,
        userType: "intern",
        reason: "Polsterkontur angepasst",
        status: "ersetzt",
        basedOnRevision: "01",
        drawings: ["Zeichnung_4711_Stand02.pdf"],
        photos: ["Foto_Muster_02", "Vergleich_01_02"],
        documents: [],
        bomItems: ["Bezug Vorderseite", "Schaum Einlage V2", "Garn X"],
        files: ["CAD_4711_REV02"],
      },
      {
        id: "rev-03",
        partId: ids.part4711,
        revision: "03",
        title: "Schnittänderung",
        date: "2020-05-18",
        createdByUserId: ids.tom,
        userType: "intern",
        reason: "Schnittkontur",
        status: "ersetzt",
        basedOnRevision: "02",
        drawings: ["Schnitt_4711_Stand03.dxf", "Zeichnung_4711_Stand03.pdf"],
        photos: ["Foto_Schnitt_03"],
        documents: ["Aenderungsbericht_03.pdf"],
        bomItems: ["Bezug Vorderseite", "Schaum Einlage V2", "Garn X"],
        files: ["Schnitt_4711_REV03"],
      },
      {
        id: "rev-04",
        partId: ids.part4711,
        revision: "04",
        title: "Nahtänderung",
        date: "2021-02-11",
        createdByUserId: ids.lena,
        userType: "intern",
        reason: "Doppelnaht Serienstand",
        status: "ersetzt",
        basedOnRevision: "03",
        drawings: ["Zeichnung_4711_Stand04.pdf"],
        photos: ["Nahtbild_04_vorher", "Nahtbild_04_nachher"],
        documents: ["Nahtspezifikation_04.pdf"],
        bomItems: ["Bezug Vorderseite", "Schaum Einlage V2", "Garn Y Doppelnaht"],
        files: ["Naht_4711_REV04"],
      },
      {
        id: "rev-05",
        partId: ids.part4711,
        revision: "05",
        title: "Materialänderung – Relaunch",
        date: "2023-07-22",
        createdByUserId: ids.lena,
        userType: "intern",
        reason: "Material B + neue Farbe – freigegeben für Produktion",
        status: "relaunched",
        basedOnRevision: "04",
        relaunchedAt: "2023-08-01",
        relaunchedByUserId: ids.frank,
        drawings: ["Zeichnung_4711_Stand05.pdf", "CAD_4711_REV05"],
        photos: ["Muster_05_Freigabe", "Material_05"],
        documents: ["Freigabeprotokoll_05.pdf", "Kundenzeichnung_05.pdf"],
        bomItems: ["Bezug Material B", "Schaum Einlage V2", "Garn Y"],
        files: ["Material_4711_REV05"],
      },
      {
        id: "rev-06",
        partId: ids.part4711,
        revision: "06",
        title: "Externe Schnittentwicklung",
        date: "2026-09-25",
        createdByUserId: ids.max,
        userType: "extern",
        company: "SchnittPartner GmbH",
        reason: "Anpassung Schnittkontur nach LOP",
        status: "zur_pruefung",
        basedOnRevision: "05",
        drawings: ["CAD_4711_REV06", "Schnitt_4711_REV06"],
        photos: ["Upload_Extern_06"],
        documents: ["Lieferbericht_EXT.pdf"],
        bomItems: ["Bezug Material B", "Schaum Einlage V2", "Garn Y"],
        files: ["CAD_4711_REV06", "Schnitt_4711_REV06"],
      },
      {
        id: "rev-07",
        partId: ids.part4711,
        revision: "07",
        title: "Entwicklungsschleife – Anpassung nach Prüfung",
        date: "2026-09-28",
        createdByUserId: ids.tom,
        userType: "intern",
        reason: "Korrektur nach Engineering-Prüfung – Stand in Arbeit",
        status: "in_entwicklung",
        basedOnRevision: "06",
        drawings: ["CAD_4711_REV07_WIP"],
        photos: [],
        documents: ["LOP_Referenz_Nahtbild.pdf"],
        bomItems: ["Bezug Material B", "Schaum Einlage V2", "Garn Y"],
        files: ["CAD_4711_REV07"],
      },

      // Daimler Alcantara Links – Stände mit unabhängigen Profil-Ständen
      {
        id: "rev-alc-01",
        partId: "part-w990-s-alc-l",
        revision: "01",
        title: "Erststand Bezug",
        date: "2025-11-10",
        createdByUserId: ids.lena,
        userType: "intern",
        reason: "Start Bezugsentwicklung",
        status: "ersetzt",
        drawings: ["ZW_A990_ALC_L_01.pdf"],
        photos: ["Muster_ALC_01"],
        documents: [],
        bomItems: ["Alcantara A", "Schaum", "Garn 30"],
        files: ["ZW_A990_ALC_L_01.pdf"],
        weightGrams: 1180,
        componentStands: [
          { partId: "part-w990-alc-l-p01", revision: "01", carriedOver: false },
          { partId: "part-w990-alc-l-p02", revision: "01", carriedOver: false },
          { partId: "part-w990-alc-l-p03", revision: "01", carriedOver: false },
          { partId: "part-w990-alc-l-p04", revision: "01", carriedOver: false },
        ],
      },
      {
        id: "rev-alc-02",
        partId: "part-w990-s-alc-l",
        revision: "02",
        title: "LOP Nahtbild",
        date: "2026-02-14",
        createdByUserId: ids.lena,
        userType: "intern",
        reason: "LOP-Punkte Nahtbild abgearbeitet – Profile unverändert übernommen",
        status: "ersetzt",
        basedOnRevision: "01",
        drawings: ["ZW_A990_ALC_L_02.pdf"],
        photos: ["Naht_02_vorher", "Naht_02_nachher"],
        documents: ["LOP_Abgleich_02.pdf"],
        bomItems: ["Alcantara A", "Schaum", "Garn 30"],
        files: ["ZW_A990_ALC_L_02.pdf"],
        weightGrams: 1165,
        componentStands: [
          { partId: "part-w990-alc-l-p01", revision: "01", carriedOver: true },
          { partId: "part-w990-alc-l-p02", revision: "01", carriedOver: true },
          { partId: "part-w990-alc-l-p03", revision: "01", carriedOver: true },
          { partId: "part-w990-alc-l-p04", revision: "01", carriedOver: true },
        ],
      },
      {
        id: "rev-alc-03",
        partId: "part-w990-s-alc-l",
        revision: "03",
        title: "Relaunch Stand 03",
        date: "2026-06-01",
        createdByUserId: ids.david,
        userType: "intern",
        reason: "Verantwortlicher gibt Stand frei – Profil Sitzseite mitgezogen, Rest 1:1",
        status: "relaunched",
        basedOnRevision: "02",
        relaunchedAt: "2026-06-05",
        relaunchedByUserId: ids.frank,
        drawings: ["ZW_A990_ALC_L_03.pdf", "Kundenzeichnung_03.pdf"],
        photos: ["Freigabemuster_03"],
        documents: ["Relaunch_Protokoll_03.pdf", "Stückliste_03.xlsx"],
        bomItems: ["Alcantara A", "Schaum V2", "Garn 30", "Clip Set"],
        files: ["ZW_A990_ALC_L_03.pdf"],
        weightGrams: 1210,
        componentStands: [
          { partId: "part-w990-alc-l-p01", revision: "02", carriedOver: false },
          { partId: "part-w990-alc-l-p02", revision: "01", carriedOver: true },
          { partId: "part-w990-alc-l-p03", revision: "01", carriedOver: true },
          { partId: "part-w990-alc-l-p04", revision: "01", carriedOver: true },
        ],
      },
      {
        id: "rev-alc-04",
        partId: "part-w990-s-alc-l",
        revision: "04",
        title: "Neue Entwicklungsschleife",
        date: "2026-09-15",
        createdByUserId: ids.lena,
        userType: "intern",
        reason:
          "Neuer Auftrag – Bezug geändert, geteiltes OKR-Profil und Lehne 1:1 übernommen (kein CAD nötig)",
        status: "in_entwicklung",
        basedOnRevision: "03",
        drawings: ["ZW_A990_ALC_L_04_WIP.pdf"],
        photos: ["Versuch_04"],
        documents: ["Auftrag_Entwicklungsschleife.pdf"],
        bomItems: ["Alcantara A", "Schaum V2", "Garn 30", "Clip Set"],
        files: ["ZW_A990_ALC_L_04_WIP.pdf"],
        weightGrams: 1195,
        componentStands: [
          { partId: "part-w990-alc-l-p01", revision: "02", carriedOver: true },
          { partId: "part-w990-alc-l-p02", revision: "02", carriedOver: false },
          { partId: "part-w990-alc-l-p03", revision: "01", carriedOver: true },
          { partId: "part-w990-alc-l-p04", revision: "01", carriedOver: true },
        ],
      },
      // Spiegelteil: gleiche Stände referenziert über Sync-Hinweis in UI; eigene Stände für Doku
      {
        id: "rev-alc-r-03",
        partId: "part-w990-s-alc-r",
        revision: "03",
        title: "Spiegel von Stand 03 Links",
        date: "2026-06-05",
        createdByUserId: ids.david,
        userType: "intern",
        reason: "Gespiegelt von A990-1S-ALC-L Stand 03 – Doku/Kunde",
        status: "relaunched",
        basedOnRevision: "02",
        relaunchedAt: "2026-06-05",
        relaunchedByUserId: ids.frank,
        drawings: ["ZW_A990_ALC_R_03.pdf"],
        photos: [],
        documents: ["Hinweis_Spiegel_von_L.pdf"],
        bomItems: ["Alcantara A", "Schaum V2", "Garn 30", "Clip Set"],
        files: ["ZW_A990_ALC_R_03.pdf"],
      },
      {
        id: "rev-alc-r-04",
        partId: "part-w990-s-alc-r",
        revision: "04",
        title: "Spiegel – Schleife 04",
        date: "2026-09-15",
        createdByUserId: ids.lena,
        userType: "intern",
        reason: "Mitgeführt zur Entwicklungsschleife Links",
        status: "in_entwicklung",
        basedOnRevision: "03",
        drawings: ["ZW_A990_ALC_R_04_WIP.pdf"],
        photos: [],
        documents: [],
        bomItems: ["Alcantara A", "Schaum V2", "Garn 30", "Clip Set"],
        files: ["ZW_A990_ALC_R_04_WIP.pdf"],
      },

      {
        id: "rev-m01",
        partId: ids.part8820,
        revision: "01",
        title: "Erststand",
        date: "2025-11-02",
        createdByUserId: ids.david,
        userType: "intern",
        reason: "Start",
        status: "freigegeben",
        drawings: ["CAD_8820_REV01"],
        photos: ["Muster_8820_01"],
        documents: [],
        bomItems: ["Leder", "Schaum"],
        files: ["CAD_8820_REV01"],
      },
      {
        id: "rev-m03",
        partId: ids.part8820,
        revision: "03",
        title: "Externe Anpassung",
        date: "2026-09-10",
        createdByUserId: ids.max,
        userType: "extern",
        company: "SchnittPartner GmbH",
        reason: "Kontur Seitenwange",
        status: "zur_pruefung",
        basedOnRevision: "01",
        drawings: ["CAD_8820_REV03"],
        photos: [],
        documents: ["Extern_Bericht.pdf"],
        bomItems: ["Leder", "Schaum"],
        files: ["CAD_8820_REV03"],
      },
      // Profile – eigene Zeichnungen je Stand
      {
        id: "rev-p01-01",
        partId: "part-w990-alc-l-p01",
        revision: "01",
        title: "Erstzeichnung OKR Sitzseite",
        date: "2026-03-01",
        createdByUserId: "u-sara",
        userType: "intern",
        reason: "CAD-Erstauslegung Profil",
        status: "ersetzt",
        drawings: ["ZW_A990_OKR_SITZ_01.dwg", "ZW_A990_OKR_SITZ_01.pdf"],
        photos: [],
        documents: ["CAD_Auftrag_P01.pdf"],
        bomItems: ["OKR-Profil Typ A", "Länge nach Spec"],
        files: ["ZW_A990_OKR_SITZ_01.pdf"],
      },
      {
        id: "rev-p01-02",
        partId: "part-w990-alc-l-p01",
        revision: "02",
        title: "Anpassung Kontur Schaum",
        date: "2026-06-02",
        createdByUserId: "u-sara",
        userType: "intern",
        reason:
          "Kontur an freigegebenen Schaum Stand 02 – wirkt auf Alcantara, Leder und Stoff",
        status: "relaunched",
        basedOnRevision: "01",
        relaunchedAt: "2026-06-05",
        relaunchedByUserId: ids.david,
        drawings: ["ZW_A990_OKR_SITZ_02.dwg", "ZW_A990_OKR_SITZ_02.pdf"],
        photos: ["Profil_Muster_P01"],
        documents: ["Freigabe_Profil_OKR_SITZ.pdf", "Impact_Alcantara_Leder_Stoff.pdf"],
        bomItems: ["OKR-Profil Typ A", "Länge 482 mm"],
        files: ["ZW_A990_OKR_SITZ_02.pdf"],
      },
      {
        id: "rev-p02-01",
        partId: "part-w990-alc-l-p02",
        revision: "01",
        title: "Erstzeichnung OKR Lehne",
        date: "2026-03-05",
        createdByUserId: "u-sara",
        userType: "intern",
        reason: "CAD-Erstauslegung",
        status: "relaunched",
        relaunchedAt: "2026-04-10",
        relaunchedByUserId: ids.david,
        drawings: ["ZW_A990_ALC_L_P02_01.pdf"],
        photos: [],
        documents: [],
        bomItems: ["OKR-Profil Typ B"],
        files: ["ZW_A990_ALC_L_P02_01.pdf"],
      },
      {
        id: "rev-p02-02",
        partId: "part-w990-alc-l-p02",
        revision: "02",
        title: "CAD-Änderung nach LOP",
        date: "2026-09-10",
        createdByUserId: "u-sara",
        userType: "intern",
        reason: "Neue Zeichnung – in Entwicklung",
        status: "in_entwicklung",
        basedOnRevision: "01",
        drawings: ["ZW_A990_ALC_L_P02_02_WIP.dwg"],
        photos: [],
        documents: ["CAD_Auftrag_Aenderung.pdf"],
        bomItems: ["OKR-Profil Typ B"],
        files: ["ZW_A990_ALC_L_P02_02_WIP.dwg"],
      },
      {
        id: "rev-p03-01",
        partId: "part-w990-alc-l-p03",
        revision: "01",
        title: "Erstzeichnung Seitenwange",
        date: "2026-05-20",
        createdByUserId: "u-sara",
        userType: "intern",
        reason: "CAD-Zeichnung Profil Seitenwange",
        status: "zur_pruefung",
        drawings: ["ZW_A990_ALC_L_P03_01.pdf"],
        photos: [],
        documents: [],
        bomItems: ["OKR-Profil Seitenwange"],
        files: ["ZW_A990_ALC_L_P03_01.pdf"],
      },
      {
        id: "rev-p04-01",
        partId: "part-w990-alc-l-p04",
        revision: "01",
        title: "Clip-Profil Abschluss",
        date: "2026-05-22",
        createdByUserId: "u-jonas",
        userType: "intern",
        reason: "Befestigungsprofil",
        status: "freigegeben",
        drawings: ["ZW_A990_ALC_L_P04_01.pdf"],
        photos: [],
        documents: [],
        bomItems: ["Clip-Profil"],
        files: ["ZW_A990_ALC_L_P04_01.pdf"],
      },
      // Leder – nutzt geteiltes OKR-Profil
      {
        id: "rev-led-01",
        partId: "part-w990-s-led-l",
        revision: "01",
        title: "Erststand Leder",
        date: "2026-04-10",
        createdByUserId: ids.lena,
        userType: "intern",
        reason: "Start Lederbezug – OKR Sitzseite vom gemeinsamen Profil",
        status: "relaunched",
        relaunchedAt: "2026-05-01",
        relaunchedByUserId: ids.david,
        drawings: ["ZW_A990_LED_L_01.pdf"],
        photos: [],
        documents: [],
        bomItems: ["Leder Nappa", "Garn 30"],
        files: ["ZW_A990_LED_L_01.pdf"],
        componentStands: [
          { partId: "part-w990-alc-l-p01", revision: "02", carriedOver: false },
        ],
      },
      {
        id: "rev-led-02",
        partId: "part-w990-s-led-l",
        revision: "02",
        title: "Nahtkorrektur Leder",
        date: "2026-08-20",
        createdByUserId: ids.lena,
        userType: "intern",
        reason: "Nur Bezug geändert – geteiltes OKR-Profil 1:1 übernommen",
        status: "in_entwicklung",
        basedOnRevision: "01",
        drawings: ["ZW_A990_LED_L_02_WIP.pdf"],
        photos: [],
        documents: [],
        bomItems: ["Leder Nappa", "Garn 30"],
        files: ["ZW_A990_LED_L_02_WIP.pdf"],
        componentStands: [
          { partId: "part-w990-alc-l-p01", revision: "02", carriedOver: true },
        ],
      },
      {
        id: "rev-stof-01",
        partId: "part-w990-s-stof-l",
        revision: "01",
        title: "Erststand Stoff",
        date: "2026-07-01",
        createdByUserId: ids.lena,
        userType: "intern",
        reason: "Stoffbezug mit gleichem OKR-Profil wie Alcantara/Leder",
        status: "in_entwicklung",
        drawings: ["ZW_A990_STF_L_01.pdf"],
        photos: [],
        documents: [],
        bomItems: ["Stoff Serie B", "Garn 28"],
        files: ["ZW_A990_STF_L_01.pdf"],
        componentStands: [
          { partId: "part-w990-alc-l-p01", revision: "02", carriedOver: false },
        ],
      },
      // Schaumteile – eigene Revisionsstände
      {
        id: "rev-sch-s-01",
        partId: "part-w990-schaum-sitz",
        revision: "01",
        title: "Erstauslegung Sitzschaum",
        date: "2025-12-01",
        createdByUserId: ids.david,
        userType: "intern",
        reason: "Schaumkanäle für OKR",
        status: "ersetzt",
        drawings: ["ZW_A990_SCH_S_01.pdf"],
        photos: [],
        documents: [],
        bomItems: ["PUR-Schaum Sitz"],
        files: ["ZW_A990_SCH_S_01.pdf"],
      },
      {
        id: "rev-sch-s-02",
        partId: "part-w990-schaum-sitz",
        revision: "02",
        title: "Kanal-Kontur freigegeben",
        date: "2026-05-15",
        createdByUserId: ids.david,
        userType: "intern",
        reason: "Abstimmung Profil A990-OKR-SITZ – Relaunch",
        status: "relaunched",
        basedOnRevision: "01",
        relaunchedAt: "2026-05-20",
        relaunchedByUserId: ids.frank,
        drawings: ["ZW_A990_SCH_S_02.pdf"],
        photos: ["Schaum_Schnitt_02"],
        documents: ["Freigabe_Schaum_Sitz.pdf"],
        bomItems: ["PUR-Schaum Sitz V2"],
        files: ["ZW_A990_SCH_S_02.pdf"],
      },
      {
        id: "rev-sch-s-03",
        partId: "part-w990-schaum-sitz",
        revision: "03",
        title: "Härtezone Seite",
        date: "2026-09-01",
        createdByUserId: "u-jonas",
        userType: "intern",
        reason: "Neue Härtezone – in Entwicklung",
        status: "in_entwicklung",
        basedOnRevision: "02",
        drawings: ["ZW_A990_SCH_S_03_WIP.pdf"],
        photos: [],
        documents: ["Auftrag_Schaum_03.pdf"],
        bomItems: ["PUR-Schaum Sitz V2", "Härteeinlage"],
        files: ["ZW_A990_SCH_S_03_WIP.pdf"],
      },
      {
        id: "rev-sch-l-01",
        partId: "part-w990-schaum-lehne",
        revision: "01",
        title: "Erstauslegung Lehnenschaum",
        date: "2026-01-20",
        createdByUserId: "u-jonas",
        userType: "intern",
        reason: "Start Lehne",
        status: "ersetzt",
        drawings: ["ZW_A990_SCH_L_01.pdf"],
        photos: [],
        documents: [],
        bomItems: ["PUR-Schaum Lehne"],
        files: ["ZW_A990_SCH_L_01.pdf"],
      },
      {
        id: "rev-sch-l-02",
        partId: "part-w990-schaum-lehne",
        revision: "02",
        title: "Relaunch Lehnenschaum",
        date: "2026-06-10",
        createdByUserId: "u-jonas",
        userType: "intern",
        reason: "Kontur an Lehnenprofil",
        status: "relaunched",
        basedOnRevision: "01",
        relaunchedAt: "2026-06-12",
        relaunchedByUserId: ids.david,
        drawings: ["ZW_A990_SCH_L_02.pdf"],
        photos: [],
        documents: ["Freigabe_Schaum_Lehne.pdf"],
        bomItems: ["PUR-Schaum Lehne V2"],
        files: ["ZW_A990_SCH_L_02.pdf"],
      },
      // Kunststoffschale – Stände
      {
        id: "rev-ks-01",
        partId: "part-w990-ks-schale",
        revision: "01",
        title: "Erstauslegung Schale",
        date: "2026-02-01",
        createdByUserId: ids.david,
        userType: "intern",
        reason: "Kunststoff Komplettsitz",
        status: "ersetzt",
        drawings: ["ZW_A990_KS_01.pdf"],
        photos: [],
        documents: [],
        bomItems: ["PP-Schale"],
        files: ["ZW_A990_KS_01.pdf"],
      },
      {
        id: "rev-ks-02",
        partId: "part-w990-ks-schale",
        revision: "02",
        title: "Kontur freigegeben",
        date: "2026-07-01",
        createdByUserId: ids.david,
        userType: "intern",
        reason: "Abstimmung Bezug/Schaum",
        status: "relaunched",
        basedOnRevision: "01",
        relaunchedAt: "2026-07-05",
        relaunchedByUserId: ids.frank,
        drawings: ["ZW_A990_KS_02.pdf"],
        photos: [],
        documents: ["Freigabe_KS_02.pdf"],
        bomItems: ["PP-Schale Rev02"],
        files: ["ZW_A990_KS_02.pdf"],
      },
    ],
    tasks: [
      {
        id: "t-1",
        title: "Nahtbild Kopfstütze nacharbeiten",
        type: "naehauftrag",
        status: "in_bearbeitung",
        projectId: ids.pAudi,
        partId: ids.part4711,
        assigneeId: ids.anna,
        departmentId: "naeherei",
        priority: "kritisch",
        dueDate: "2026-09-19",
        progress: 55,
        description: "Nahtbild an Kopfstütze laut LOP nicht akzeptabel – Nacharbeit Muster.",
        createdAt: "2026-09-15T08:00:00.000Z",
        risk: "rot",
      },
      {
        id: "t-2",
        title: "Schnittkontur Rev. 07 finalisieren",
        type: "schnittentwicklung",
        status: "warten_freigabe",
        projectId: ids.pAudi,
        partId: ids.part4711,
        assigneeId: ids.tom,
        departmentId: "schnittentwicklung",
        priority: "hoch",
        dueDate: "2026-09-20",
        progress: 80,
        description: "Finale Anpassung nach Prüfung Rev. 06.",
        createdAt: "2026-09-16T09:00:00.000Z",
        risk: "orange",
      },
      {
        id: "t-3",
        title: "Muster Kopfstütze bauen",
        type: "musterbau",
        status: "warten_material",
        projectId: ids.pAudi,
        partId: ids.part4711,
        assigneeId: ids.elena,
        departmentId: "musterbau",
        priority: "hoch",
        dueDate: "2026-09-22",
        progress: 20,
        description: "Abhängig von Nähauftrag und Freigabe.",
        createdAt: "2026-09-14T10:00:00.000Z",
        risk: "orange",
      },
      {
        id: "t-4",
        title: "Dokumentation Rev. 07",
        type: "dokumentation",
        status: "offen",
        projectId: ids.pAudi,
        partId: ids.part4711,
        assigneeId: ids.sofia,
        departmentId: "dokumentation",
        priority: "normal",
        dueDate: "2026-09-30",
        progress: 0,
        description: "Technische Dokumentation nach Freigabe.",
        createdAt: "2026-09-17T11:00:00.000Z",
      },
      {
        id: "t-5",
        title: "Externe Schnittentwicklung Seitenwange",
        type: "extern",
        status: "in_bearbeitung",
        projectId: ids.pMerc,
        partId: ids.part8820,
        assigneeId: ids.max,
        departmentId: "extern",
        priority: "hoch",
        dueDate: "2026-09-25",
        progress: 40,
        description: "Auftrag EXT-2026-0042 – nur freigegebene Dateien sichtbar.",
        createdAt: "2026-09-08T08:00:00.000Z",
        risk: "orange",
      },
      {
        id: "t-6",
        title: "Freigabe Engineering Prüfung",
        type: "pruefung",
        status: "zur_pruefung",
        projectId: ids.pAudi,
        partId: ids.part4711,
        assigneeId: ids.lena,
        departmentId: "engineering",
        priority: "hoch",
        dueDate: "2026-09-18",
        progress: 90,
        description: "Prüfung Rev. 06 / Vorbereitung Rev. 07.",
        createdAt: "2026-09-17T14:00:00.000Z",
        risk: "gelb",
      },
      {
        id: "t-7",
        title: "Lederzuschnitt Muster",
        type: "zuschnittauftrag",
        status: "offen",
        projectId: ids.pAudi,
        partId: ids.part4711,
        assigneeId: ids.ion,
        departmentId: "zuschnitt",
        priority: "normal",
        dueDate: "2026-09-21",
        progress: 0,
        description: "Zuschnitt für Nacharbeitsmuster.",
        createdAt: "2026-09-16T12:00:00.000Z",
      },
      {
        id: "t-8",
        title: "Polsteraufbau Versuch",
        type: "polsterauftrag",
        status: "rueckfrage",
        projectId: ids.pBmw,
        partId: ids.part3301,
        assigneeId: ids.markus,
        departmentId: "polsterei",
        priority: "normal",
        dueDate: "2026-09-24",
        progress: 30,
        description: "Rückfrage zum Schaumtyp – Materiallieferung offen.",
        createdAt: "2026-09-12T09:00:00.000Z",
        risk: "gelb",
      },
      {
        id: "t-9",
        title: "Entwicklungsschleife · A990-1S-ALC-L · Stand 04",
        type: "entwicklungsschleife",
        status: "offen",
        projectId: "p-daimler",
        partId: "part-w990-s-alc-l",
        revisionStand: "04",
        departmentId: "engineering",
        createdByUserId: ids.frank,
        needsAssignment: true,
        priority: "hoch",
        dueDate: "2026-09-28",
        progress: 0,
        description:
          "Tobias: Für W 990 Sportsitz Alcantara Links brauchen wir eine neue Entwicklungsschleife nach LOP. Engineering bitte zuweisen.",
        createdAt: "2026-09-18T08:00:00.000Z",
        risk: "orange",
      },
      {
        id: "t-10",
        title: "Zuschnittauftrag · A990-1S-ALC-L · Stand 03",
        type: "zuschnittauftrag",
        status: "offen",
        projectId: "p-daimler",
        partId: "part-w990-s-alc-l",
        revisionStand: "03",
        departmentId: "zuschnitt",
        createdByUserId: ids.katharina,
        needsAssignment: true,
        priority: "hoch",
        dueDate: "2026-09-22",
        progress: 0,
        description:
          "Zuschnitt für freigegebenen Stand 03 – bitte Mitarbeiter aus Zuschnitt zuordnen.",
        createdAt: "2026-09-17T10:00:00.000Z",
      },
      {
        id: "t-11",
        title: "Nähauftrag · A990-1S-ALC-L · Stand 03",
        type: "naehauftrag",
        status: "offen",
        projectId: "p-daimler",
        partId: "part-w990-s-alc-l",
        revisionStand: "03",
        departmentId: "naeherei",
        createdByUserId: ids.katharina,
        needsAssignment: true,
        priority: "normal",
        dueDate: "2026-09-25",
        progress: 0,
        description: "Nähen Muster Stand 03 – Näherei weist Näher/in zu.",
        createdAt: "2026-09-17T10:05:00.000Z",
      },
      {
        id: "t-12",
        title: "Schnittentwicklung · ABC-1S-ALC-L · Stand 04",
        type: "schnittentwicklung",
        status: "offen",
        projectId: ids.pAudi,
        partId: "part-audi-bezug-l",
        revisionStand: "04",
        departmentId: "schnittentwicklung",
        createdByUserId: ids.frank,
        needsAssignment: true,
        priority: "kritisch",
        dueDate: "2026-09-20",
        progress: 0,
        description: "Schnittanpassung – bitte einem Schnittentwickler zuordnen.",
        createdAt: "2026-09-16T14:00:00.000Z",
        risk: "rot",
      },
      {
        id: "t-13",
        title: "CAD-Zeichnung · A990-ALC-L-P02 · Stand 02",
        type: "cad",
        status: "offen",
        projectId: "p-daimler",
        partId: "part-w990-alc-l-p02",
        revisionStand: "02",
        departmentId: "cad",
        createdByUserId: ids.david,
        needsAssignment: true,
        priority: "hoch",
        dueDate: "2026-09-24",
        progress: 0,
        description:
          "OKR-Profil Lehnenseite – neue CAD-Zeichnung nach LOP. CAD-Abteilung bitte Zeichner zuweisen.",
        createdAt: "2026-09-18T09:00:00.000Z",
      },
      {
        id: "t-14",
        title: "CAD-Zeichnung · A990-ALC-L-P03 · Stand 01",
        type: "cad",
        status: "offen",
        projectId: "p-daimler",
        partId: "part-w990-alc-l-p03",
        revisionStand: "01",
        departmentId: "cad",
        createdByUserId: ids.lena,
        assigneeId: "u-sara",
        needsAssignment: false,
        priority: "normal",
        dueDate: "2026-09-21",
        progress: 40,
        description: "Profil Seitenwange – Zeichnung in Prüfung, Sara zugewiesen.",
        createdAt: "2026-09-15T11:00:00.000Z",
        startedAt: "2026-09-15T13:00:00.000Z",
      },
      {
        id: "t-15",
        title: "CAD-Zeichnung · A990-OKR-SITZ · Stand 02",
        type: "cad",
        status: "erledigt",
        projectId: "p-daimler",
        partId: "part-w990-alc-l-p01",
        revisionStand: "02",
        departmentId: "cad",
        createdByUserId: ids.david,
        assigneeId: "u-sara",
        needsAssignment: false,
        priority: "hoch",
        dueDate: "2026-06-05",
        progress: 100,
        description: "Geteiltes OKR-Profil – Zeichnung freigegeben.",
        createdAt: "2026-06-01T08:00:00.000Z",
        startedAt: "2026-06-01T09:30:00.000Z",
        completedAt: "2026-06-03T16:00:00.000Z",
        timeSpentMinutes: 390,
      },
      {
        id: "t-16",
        title: "Nähauftrag · A990-1S-ALC-L · Stand 03",
        type: "naehauftrag",
        status: "erledigt",
        projectId: "p-daimler",
        partId: "part-w990-s-alc-l",
        revisionStand: "03",
        departmentId: "naeherei",
        createdByUserId: ids.lena,
        assigneeId: ids.anna,
        needsAssignment: false,
        priority: "normal",
        dueDate: "2026-06-08",
        progress: 100,
        description: "Muster nähen nach Relaunch Stand 03.",
        createdAt: "2026-06-05T07:00:00.000Z",
        startedAt: "2026-06-05T08:00:00.000Z",
        completedAt: "2026-06-06T14:30:00.000Z",
        timeSpentMinutes: 270,
      },
    ],
    lops: [
      {
        id: "lop-1",
        title: "Nahtbild an Kopfstütze nicht akzeptabel",
        description: "Kunde / Werk meldet Abweichung am Nahtbild der Kopfstütze.",
        source: "werk",
        status: "naeherei",
        projectId: ids.pAudi,
        partId: ids.part4711,
        departmentIds: ["engineering", "schnittentwicklung", "naeherei"],
        assigneeIds: [ids.lena, ids.tom, ids.anna],
        createdByUserId: ids.frank,
        createdAt: "2026-09-14T07:30:00.000Z",
        dueDate: "2026-09-20",
        photos: ["Nahtbild_Kopfstuetze_01", "Nahtbild_Kopfstuetze_02"],
        history: [
          {
            id: "lh1-1",
            at: "2026-09-14T07:30:00.000Z",
            actorUserId: ids.frank,
            action: "Erstellt",
            detail: "Meldung vom Werk",
          },
          {
            id: "lh1-2",
            at: "2026-09-14T09:15:00.000Z",
            actorUserId: ids.lena,
            action: "Bewertet",
            detail: "Nahtbild weicht vom Freigabemuster ab – Nacharbeit nötig",
          },
          {
            id: "lh1-3",
            at: "2026-09-15T11:00:00.000Z",
            actorUserId: ids.tom,
            action: "Schnitt angepasst",
            detail: "Kontur Kopfstütze Rev. vorbereitet",
          },
          {
            id: "lh1-4",
            at: "2026-09-16T14:20:00.000Z",
            actorUserId: ids.anna,
            action: "In Näherei übernommen",
            detail: "Muster in Arbeit",
          },
        ],
      },
      {
        id: "lop-2",
        title: "Schnittkontur Rev. 06 prüfen",
        description: "Interne Prüfung der externen Schnittlieferung.",
        source: "engineering",
        status: "pruefung",
        projectId: ids.pAudi,
        partId: ids.part4711,
        departmentIds: ["engineering", "schnittentwicklung"],
        assigneeIds: [ids.lena, ids.tom],
        createdByUserId: ids.lena,
        createdAt: "2026-09-26T10:00:00.000Z",
        dueDate: "2026-09-19",
        photos: ["Schnittkontur_Rev06_Markierung"],
        history: [
          {
            id: "lh2-1",
            at: "2026-09-26T10:00:00.000Z",
            actorUserId: ids.lena,
            action: "Erstellt",
          },
          {
            id: "lh2-2",
            at: "2026-09-26T11:30:00.000Z",
            actorUserId: ids.tom,
            action: "Kommentar",
            detail: "Abweichung an Außenkontur markiert – Foto angehängt",
          },
        ],
      },
      {
        id: "lop-3",
        title: "Dokumentation: Fotos fehlen",
        description: "Dokumentation meldet fehlende Musterfotos an Entwickler.",
        source: "dokumentation",
        status: "offen",
        projectId: ids.pAudi,
        partId: ids.part4711,
        departmentIds: ["dokumentation", "engineering"],
        assigneeIds: [ids.lena],
        createdByUserId: ids.sofia,
        createdAt: "2026-09-17T15:00:00.000Z",
        photos: [],
        history: [
          {
            id: "lh3-1",
            at: "2026-09-17T15:00:00.000Z",
            actorUserId: ids.sofia,
            action: "Erstellt",
            detail: "Musterfotos für Freigabeordner fehlen",
          },
        ],
      },
      {
        id: "lop-4",
        title: "Material BMW Sitzfläche verzögert",
        description: "Lieferverzögerung blockiert Polsterei.",
        source: "management",
        status: "offen",
        projectId: ids.pBmw,
        partId: ids.part3301,
        departmentIds: ["polsterei", "musterbau"],
        assigneeIds: [ids.markus],
        createdByUserId: ids.katharina,
        createdAt: "2026-09-13T08:00:00.000Z",
        dueDate: "2026-09-23",
        photos: [],
        history: [
          {
            id: "lh4-1",
            at: "2026-09-13T08:00:00.000Z",
            actorUserId: ids.katharina,
            action: "Erstellt",
            detail: "Liefertermin unklar",
          },
        ],
      },
    ],
    approvals: [
      {
        id: "a-1",
        taskId: "t-6",
        projectId: ids.pAudi,
        revisionId: "rev-06",
        decision: "offen",
        requestedAt: "2026-09-17T14:30:00.000Z",
      },
      {
        id: "a-2",
        taskId: "t-2",
        projectId: ids.pAudi,
        revisionId: "rev-07",
        decision: "offen",
        requestedAt: "2026-09-16T16:00:00.000Z",
      },
      {
        id: "a-3",
        projectId: ids.pMerc,
        revisionId: "rev-m03",
        decision: "offen",
        requestedAt: "2026-09-11T09:00:00.000Z",
      },
    ],
    substitutions: [
      {
        id: "sub-1",
        absentUserId: ids.tom,
        substituteUserId: ids.david,
        from: "2026-09-18",
        to: "2026-09-25",
        note: "Tom im Urlaub – David übernimmt Schnitt-LOPs.",
      },
    ],
    activityLog: [
      {
        id: "act-1",
        at: "2026-09-28T09:00:00.000Z",
        actorUserId: ids.tom,
        action: "Revision erstellt",
        entityType: "revision",
        entityId: "rev-07",
        detail: "Rev. 07 – Anpassung nach Prüfung",
      },
      {
        id: "act-2",
        at: "2026-09-25T11:20:00.000Z",
        actorUserId: ids.max,
        action: "Externe Revision hochgeladen",
        entityType: "revision",
        entityId: "rev-06",
        detail: "Rev. 06 – SchnittPartner GmbH",
      },
      {
        id: "act-3",
        at: "2026-09-14T07:30:00.000Z",
        actorUserId: ids.frank,
        action: "LOP erstellt",
        entityType: "lop",
        entityId: "lop-1",
        detail: "Nahtbild Kopfstütze",
      },
    ],
  };
}
